### ISSUE TITLE
Allow usage without yaml file

### ISSUE THREAD

**Issue by TotalKrill** [wanderrful/bevy_keybind#1]
I like the concept, many crates that are handling cameras, are using inputs that I cannot disable and whatnot, forcing me to copy-paste the code. 

I would love if there were some way for these crate to specify what kind of controlling inputs and events they require other than implementing the key.justpressed() way that is currently the norm. 

For this we need some kind of crate that links event, to a keybind, and that can also be changed during runtime.

**Comment by wanderrful** [comment]
Thanks for posting!

So, you mean you'd like to see some kind of "namespace" for the actions and axes? Like:
```yaml
keyboard:
  actions:
    Mouse1: SelectUnitUnderCursor

gamepad:
  actions:
    Button_X: SelectUnitUnderCursor
```

Or maybe if it were inverted, like...

```yaml
actions:
  MoveForward:
    gamepad:
      - Button_X
      - Button_A
    keyboard:
      - Q
      - F5
```

I learned recently about a similar kind of use case for this crate, called kurinji (https://crates.io/crates/kurinji) and I wonder if, although it's more deprecated because of the older Bevy version, maybe their approach is better.
